version: '3.2'

services:
    logic:
        hostname: 
            logic
        image:
            kbzjung359/toiot-logic:0.0.1
        environment: 
            LOGIC_SERVER: 0.0.0.0:8082
            LOGIC_LISTEN: 10.5.110.27:8082
            APP_SERVER: 220.70.2.5:8081
            KAFKA_BROKER: 10.5.110.1:9092
            KAFKA_GROUP: logic1
            KAFKA_TOPIC: sensor-data
            ELASTIC_SERVER: 10.5.110.1:9200
        ports:
            - 8082:8082
    
